name: Maven Build, Test, and Deployment

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest  # Change the operating system to Windows

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        distribution: 'adopt'
        java-version: '11'

    - name: Validate
      run: mvn validate

    - name: Compile
      run: mvn compile

    - name: Test
      run: mvn test

    - name: Package
      run: mvn package

    - name: Verify
      run: mvn verify

    - name: Install
      run: mvn install

    - name: Deploy
      run: mvn deploy

    - name: Display Maven goals output
      run: mvn help:describe -Dcmd=09

    - name: Build project with Maven
      run: mvn -B package --file pom.xml
